# 판다스(Pandas) 심화

In [2]:
import numpy as np
import pandas as pd
print("DataFrame: ")
data = {"col1":[2,1,9,8,7,4],
        "col2":["A","A","B",np.nan,"D","C"],
        "col3":[0,1,9,4,2,3]}
index = [1,3,2,5,0,4]
df = pd.DataFrame(data, index=index)
df

DataFrame: 


col1 col2  col3
1     2    A     0
3     1    A     1
2     9    B     9
5     8  NaN     4
0     7    D     2
4     4    C     3

In [8]:
# index axis=0(행)을 축으로 정렬
df = df.sort_index(axis=0)
df

col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

In [9]:
# index axis=1(열)을 축으로 정렬
df = df.sort_index(axis=1, ascending=False)
df

col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

In [10]:
# sort_value
sorted_df1 = df.sort_values("col1", ascending=True)
sorted_df1

col3 col2  col1
3     1    A     1
1     0    A     2
4     3    C     4
0     2    D     7
5     4  NaN     8
2     9    B     9

In [12]:
# sort_value2
sorted_df2 = df.sort_values(["col2", "col1"], ascending=[True,False])
sorted_df2

col3 col2  col1
1     0    A     2
3     1    A     1
2     9    B     9
4     3    C     4
0     2    D     7
5     4  NaN     8

In [13]:
x = np.random.randint(1,5,size=(10,5))
x

array([[3, 4, 3, 3, 1],
       [1, 2, 3, 4, 2],
       [4, 2, 3, 4, 3],
       [4, 2, 4, 2, 4],
       [3, 4, 1, 3, 1],
       [2, 3, 3, 4, 2],
       [2, 2, 2, 1, 4],
       [3, 1, 1, 4, 3],
       [1, 4, 2, 1, 2],
       [3, 1, 1, 3, 4]], dtype=int32)

In [14]:
x = np.random.rand(10,5)
x

array([[0.27742231, 0.55125408, 0.30913462, 0.88469321, 0.72464872],
       [0.18265556, 0.44799429, 0.27622994, 0.83812208, 0.56112267],
       [0.77236916, 0.83466298, 0.45113305, 0.33014715, 0.7338592 ],
       [0.402861  , 0.67324977, 0.45637822, 0.54596592, 0.01231089],
       [0.15435676, 0.45907782, 0.30223321, 0.06354066, 0.09247927],
       [0.3935321 , 0.04953279, 0.64966774, 0.83829607, 0.40023815],
       [0.13224948, 0.30000606, 0.34892739, 0.29006416, 0.32627781],
       [0.53998872, 0.81969695, 0.97957036, 0.35344865, 0.92099056],
       [0.8095402 , 0.76383746, 0.55015776, 0.380314  , 0.48658953],
       [0.21365997, 0.10643243, 0.0656918 , 0.42560215, 0.90184846]])

In [16]:
x = np.random.normal(5,3,(10,5))
x

array([[ 4.12919599,  0.52998596,  4.60537855,  4.82489137,  3.91449523],
       [ 3.05898074,  2.60644481,  7.89056139,  8.47334884,  4.02292256],
       [ 2.5157916 ,  2.74972583, 10.6088794 ,  7.08751289,  6.11293351],
       [ 1.69438071,  4.56355974,  3.25685207,  9.21118554,  3.49173961],
       [ 5.52625261,  6.66232147,  2.19301666,  3.50444506,  3.0321992 ],
       [ 4.13949371,  6.79557435,  3.90672509,  4.04963514,  5.96038398],
       [ 4.49441586,  8.21731821,  0.72468393,  7.31777509,  7.74261236],
       [ 7.07075175,  2.99208301,  8.49064353,  3.07900286,  4.54553263],
       [ 6.39058039,  4.6805122 ,  5.41184479,  9.22277605,  2.7665564 ],
       [13.01640954,  0.59285095,  6.44135891,  6.06102054,  2.79909105]])