In [1]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#     data = f.write('*반가워요.')
#     print("저장되었습니다.")
# !pwd

# 넘파이(numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

## 1차원과 속성들

In [2]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4]) #    <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [3]:
narr1 = np.array([1,2,3,4]) # int64
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [4]:
narr4 = np.zeros((2,2),dtype='int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))


[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [5]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim, arr1.dtype, arr1.shape, arr1.size, type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [7]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/ 데이터타입:', arr2.dtype,'/ 형태:', arr2.shape, '/ 크기:',arr2.size, type(arr2),arr2)
print('차원:',arr3.ndim,'/ 데이터타입:', arr3.dtype,'/ 형태:', arr3.shape, '/ 크기:',arr3.size, type(arr3),arr3)
print('차원:',arr4.ndim,'/ 데이터타입:', arr4.dtype,'/ 형태:', arr4.shape, '/ 크기:',arr4.size, type(arr4),arr4)
print('차원:',arr5.ndim,'/ 데이터타입:', arr5.dtype,'/ 형태:', arr5.shape, '/ 크기:',arr5.size, type(arr5),arr5)
print('차원:',arr6.ndim,'/ 데이터타입:', arr6.dtype,'/ 형태:', arr6.shape, '/ 크기:',arr6.size, type(arr6),arr6)

차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 / 형태: (2, 5) / 크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 / 데이터타입: int64 / 형태: (5, 2) / 크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 / 데이터타입: int64 / 형태: (3, 3, 3) / 크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [8]:
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*23)
print(t2)
print("="*23)
print(t3)
print("="*23)
print(t4)
print("="*23)
print(t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [9]:
# test
print(t1[1][2:5])
print(t4)
print(t4[1:3,2:4])
print(t4[1:3,4:6])
print(t4 % 2 == 0)

[10 11 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[10 11]
 [17 18]]
[[12 13]
 [19 20]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [10]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [11]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [12]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]) #.reshape(1,3)
print(br1)
print(br2)
# 스칼라와 연산
print("=====스칼라와 연산=====")
print(br1)
print(br1+3)
print(br1*2)
# 2D 와 1D 의 연산
print("=====2D 와 1D 의 연산=====")
print(br2)
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[11 22 33]
=====스칼라와 연산=====
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=====2D 와 1D 의 연산=====
[11 22 33]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [13]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint() : 균일 분포의 정수 난수
- np.random.rand() : 0부터 1사이의 균일 분포 난수 생성
- np.random.randn() : 표준 정규 분포 난수 생성
- np.random.normal() : 정규 분포 난수 생성

In [14]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[109, 192,  77],
        [114, 254, 154],
        [142, 102,  34]],

       [[ 11, 174, 145],
        [ 55,   1,  95],
        [138, 180,  71]],

       [[210,  72,  70],
        [248,   5, 250],
        [176,  72,  58]]], dtype=int32)

In [15]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 118.85185185185185 표준편차: 73.01075704797748 최소값: 1 최대값: 254


In [16]:
print(len(x.flatten()))

27


In [17]:
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22


In [22]:
# size = (10,5)
x = np.random.rand(10,5)
x

array([[0.35440215, 0.57812244, 0.32764114, 0.8116618 , 0.49390061],
       [0.28397121, 0.12024567, 0.28592382, 0.11210813, 0.91607747],
       [0.64051858, 0.1942363 , 0.0552804 , 0.66078443, 0.59857743],
       [0.89745936, 0.04173478, 0.34387122, 0.63506375, 0.01464071],
       [0.9343131 , 0.62262257, 0.83540958, 0.18543834, 0.70086724],
       [0.32943071, 0.31009106, 0.87650136, 0.20076256, 0.77488361],
       [0.1142548 , 0.86327545, 0.57066241, 0.95294421, 0.81849395],
       [0.49194016, 0.43265381, 0.04259633, 0.94967613, 0.62728508],
       [0.44327967, 0.98961473, 0.61245035, 0.84486816, 0.10039108],
       [0.69242255, 0.48615348, 0.28421341, 0.48042039, 0.87727524]])

In [26]:
x = np.random.normal(5,3,(10,5))  # 평균이 , 표준편차 3
print(x)
print(np.mean(x), np.std(x), x.min(), x.max())

[[ 8.08161048  6.7660075   3.26272772  8.33813323  5.29538523]
 [ 5.63548811  7.34592456  5.78950581  5.36052461  9.63899356]
 [10.46372268  5.25893036 -0.74447171  5.31786039 12.02867846]
 [ 3.09926016  9.19521121  9.87596635  3.65028926  4.54109011]
 [10.5181167   1.90674813  2.06104555  8.21982004  5.82529731]
 [11.28828786  4.53534731 -0.94381645  1.90190043 -0.82608805]
 [ 6.48875118 -0.9444344   8.38231168  3.65139153  6.42990569]
 [ 2.2111234   1.36358983  5.66644099  2.06012529 -1.0095638 ]
 [ 4.46661069  1.94016382  9.16125199  1.49949192 -0.30003513]
 [ 3.73493323  6.13001557  5.15587579  5.63793655 -2.17955502]]
4.8446765540627315 3.5576205080897183 -2.1795550171153 12.028678459083782


In [27]:
x = np.random.randn(10,5)
print(x)
print(np.mean(x), np.std(x), x.min(), x.max())

[[ 1.94854147 -1.34122991  0.16616229  0.03099945 -1.09042658]
 [-0.09420555  0.48536077  1.28802829 -0.26516332 -0.69906524]
 [-0.38189607 -0.74609176 -0.17649478  1.48184502  0.15134686]
 [ 0.23592649 -1.34033435  1.8489522   2.24144969 -1.6932407 ]
 [-0.06164161  1.60636594  1.1379711  -0.50990587 -1.32475414]
 [-0.90573393 -0.55340525 -1.28672386  1.34703358  0.63692363]
 [-0.29802278  0.57139607 -1.46363108 -1.34937723 -1.0937861 ]
 [ 1.04169278 -0.28677169 -0.58712807 -1.19081197 -0.60851357]
 [-0.01303402 -0.04377329  0.56370367 -0.71092853 -0.30161286]
 [ 0.31485667 -1.24575124 -1.3313076  -0.90731259  0.51045976]]
-0.12586119589487788 0.9979303619558947 -1.6932407002833416 2.24144969417631


In [28]:
x = np.array([3,4,45,43,65,0,0,0,24362,6,45,6,432,562])
print("x의 개수", len(x))
print("x의 개수", np.count_nonzero(x))
print("0의 개수", len(x) - np.count_nonzero(x))

x의 개수 14
x의 개수 11
0의 개수 3


In [32]:
print(np.mean(x))
print(x.mean())
print(np.var(x))
print(x.var())
print(np.std(x))
print(x.std())
print(x.max())
print(x.min())
print(np.median(x))

1826.642857142857
1826.642857142857
39093356.8010204
39093356.8010204
6252.468056777291
6252.468056777291
24362
0
24.5


In [33]:
print(np.percentile(x,0))  # 최소값
print(np.percentile(x,25))  # 제 1사분위수
print(np.percentile(x,50))  # 중앙값, 제 2사분위수
print(np.percentile(x,75))  # 제 3사분위수
print(np.percentile(x,100))  # 최대값

0.0
3.25
24.5
60.0
24362.0


# 판다스(pandas)

- 시리즈(series)
- 데이터프레임(dataframe)

In [19]:
import numpy as np
import pandas as pd

In [22]:
data1 = np.arange(1,11)
# print(data1)
data2 = pd.Series(data1)
print(data2)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [31]:
data3 = pd.Series([1,2,3,4,5,6,7], dtype="float")
print(data3)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64


In [33]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [48]:
# 판다수 시리즈 딕셔너리데이터
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
# population_dict.keys()
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
32976
32976


In [50]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=['a','b','c'],columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [67]:
# 테스트
import numpy as np
import pandas as pd

# 두개의 시리즈 데이터
print("인구수 시리즈 데이터 : ")
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
population = pd.Series(population_dict)
print(population)

print("GDP 시리즈 데이터 : ")
GDP_dict = {
    'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa':2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print("데이터 프레임 생성 : ")
country = pd.DataFrame({'population':population, 'gdp':GDP})
country.index.name = 'Country'    # d인덱스 이름을 지정
country.columns.name = "Info"
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)

인구수 시리즈 데이터 : 
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터 : 
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성 : 
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 2


In [134]:
country.loc['korea'], country.loc['usa']
country.iloc[2], country.iloc[1]

(Info
 population       141178.0
 gdp           140925000.0
 gdp_per        998.207936
 Name: china, dtype: object,
 Info
 population         12622.0
 gdp            516700000.0
 gdp_per       40936.460149
 Name: japan, dtype: object)

In [74]:
country.iloc[0:2, :1]

Info     population
Country            
korea          5182
japan         12622

In [84]:
# 컬럼추가
# country['test'] = [11,22,33,44]
# country = country.drop('test', axis=1)  # 컬럼삭제
gdpper = country['gdp'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [107]:
# 행추가
country.loc['india'] = [142222, 150505000, 'NaN']
country.loc['india', 'gdp_per'] = country.loc['india', 'gdp'] / country.loc['india', 'population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [108]:
# 행추가 방법2
africa = pd.Series(data = [123456,7777777], index = ['population', 'gdp'])
country.loc['africa'] = africa
country.loc['africa', 'gdp_per'] = country.loc['africa', 'gdp'] / country.loc['africa', 'population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935
africa     123456.0  7.777777e+06     63.000397

In [105]:
# 결속값(NaN) 확인
country.isnull() #.sum()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
africa        False  False    False

In [109]:
# 열제거 drop(이름, axis=0)
country = country.drop('africa', axis=0) # inplace = True
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [115]:
# 테스트1 조건
country[country['population'] > 140000]

Info     population          gdp      gdp_per
Country                                      
china      141178.0  140925000.0   998.207936
india      142222.0  150505000.0  1058.239935

In [116]:
# 테스트2 조건, 슬라이싱 (loc, iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

In [168]:
# 문제1
import pandas as pd
score = pd.DataFrame([[80,70,80],[60,70,80],[70,90,80]], index=['홍길동','박철수','김영희'],columns=['국어','수학','영어'])
score

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [169]:
# 문제2
# 박철수의 국어와 수학 점수만 출력하라
score.iloc[1:2, :2]

국어  수학
박철수  60  70

In [170]:
# 문제 3
# 수학이 70점 이상인 사람 모든 행을 출력하라
score[score['수학'] >= 70]

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [171]:
# 문제 4
# 모든 과목의 평균점수를 마지막 컬럼에 넣고
# "평균"이라는 이름으로 만들어 넣어라
avg = (score['국어'] + score['수학'] + score['영어']) / 3
score['평균'] = avg
score

국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000

In [174]:
# 문제 5
# 전학 온 학생을 추가하라 (최자바 55 95 70)
score.loc['최자바'] = [55, 95, 70, "NaN"]
score['평균'] = (score['국어'] + score['수학'] + score['영어']) / 3
score

국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000
최자바  55  95  70  73.333333

In [175]:
score

국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000
최자바  55  95  70  73.333333

In [ ]:
# 리스폰에 튜플로 저장하는 방법
data =[
    ('홍길동', 80, 70 80),
    ('박철수', 80, 70 80),
    ('김영희 리스폰에 튜플로 저장하는 방법
data =[
    ('홍길동', 80, 70 80),
    ('박철수', 80, 70 80),
    ('김영희', 80, 70 80),
]
df = pd.DataFramge(data, columns-['이름', '국어', '수학', '영어'])
df